/**
 * Mapeamento de nomes de países para emojis de bandeiras
 * Suporta nomes em português e inglês
 */
const countryFlags: Record<string, string> = {
  // Países em português
  'Brasil': '🇧🇷',
  'Estados Unidos': '🇺🇸',
  'Estados Unidos da América': '🇺🇸',
  'Reino Unido': '🇬🇧',
  'França': '🇫🇷',
  'Alemanha': '🇩🇪',
  'Itália': '🇮🇹',
  'Espanha': '🇪🇸',
  'Portugal': '🇵🇹',
  'Argentina': '🇦🇷',
  'Chile': '🇨🇱',
  'Colômbia': '🇨🇴',
  'México': '🇲🇽',
  'Peru': '🇵🇪',
  'Uruguai': '🇺🇾',
  'Paraguai': '🇵🇾',
  'Venezuela': '🇻🇪',
  'Equador': '🇪🇨',
  'Bolívia': '🇧🇴',
  'Japão': '🇯🇵',
  'China': '🇨🇳',
  'Índia': '🇮🇳',
  'Coreia do Sul': '🇰🇷',
  'Coreia do Norte': '🇰🇵',
  'Tailândia': '🇹🇭',
  'Vietnã': '🇻🇳',
  'Indonésia': '🇮🇩',
  'Malásia': '🇲🇾',
  'Singapura': '🇸🇬',
  'Filipinas': '🇵🇭',
  'Austrália': '🇦🇺',
  'Nova Zelândia': '🇳🇿',
  'Rússia': '🇷🇺',
  'Turquia': '🇹🇷',
  'Grécia': '🇬🇷',
  'Países Baixos': '🇳🇱',
  'Holanda': '🇳🇱',
  'Bélgica': '🇧🇪',
  'Suíça': '🇨🇭',
  'Áustria': '🇦🇹',
  'Suécia': '🇸🇪',
  'Noruega': '🇳🇴',
  'Dinamarca': '🇩🇰',
  'Finlândia': '🇫🇮',
  'Polônia': '🇵🇱',
  'República Tcheca': '🇨🇿',
  'Hungria': '🇭🇺',
  'Romênia': '🇷🇴',
  'Bulgária': '🇧🇬',
  'Croácia': '🇭🇷',
  'Sérvia': '🇷🇸',
  'Eslováquia': '🇸🇰',
  'Eslovênia': '🇸🇮',
  'Irlanda': '🇮🇪',
  'Islândia': '🇮🇸',
  'Luxemburgo': '🇱🇺',
  'Mônaco': '🇲🇨',
  'Liechtenstein': '🇱🇮',
  'Andorra': '🇦🇩',
  'San Marino': '🇸🇲',
  'Vaticano': '🇻🇦',
  'Malta': '🇲🇹',
  'Chipre': '🇨🇾',
  'Egito': '🇪🇬',
  'África do Sul': '🇿🇦',
  'Marrocos': '🇲🇦',
  'Tunísia': '🇹🇳',
  'Turquemenistão': '🇹🇲',
  'Argélia': '🇩🇿',
  'Quênia': '🇰🇪',
  'Etiópia': '🇪🇹',
  'Nigéria': '🇳🇬',
  'Gana': '🇬🇭',
  'Senegal': '🇸🇳',
  'Costa Rica': '🇨🇷',
  'Panamá': '🇵🇦',
  'Guatemala': '🇬🇹',
  'Honduras': '🇭🇳',
  'Nicarágua': '🇳🇮',
  'El Salvador': '🇸🇻',
  'Cuba': '🇨🇺',
  'República Dominicana': '🇩🇴',
  'Jamaica': '🇯🇲',
  'Trinidad e Tobago': '🇹🇹',
  'Bahamas': '🇧🇸',
  'Barbados': '🇧🇧',
  'Israel': '🇮🇱',
  'Emirados Árabes Unidos': '🇦🇪',
  'Arábia Saudita': '🇸🇦',
  'Catar': '🇶🇦',
  'Kuwait': '🇰🇼',
  'Omã': '🇴🇲',
  'Bahrein': '🇧🇭',
  'Jordânia': '🇯🇴',
  'Líbano': '🇱🇧',
  'Síria': '🇸🇾',
  'Iraque': '🇮🇶',
  'Irã': '🇮🇷',
  'Paquistão': '🇵🇰',
  'Bangladesh': '🇧🇩',
  'Sri Lanka': '🇱🇰',
  'Nepal': '🇳🇵',
  'Butão': '🇧🇹',
  'Myanmar': '🇲🇲',
  'Camboja': '🇰🇭',
  'Laos': '🇱🇦',
  'Mongólia': '🇲🇳',
  'Cazaquistão': '🇰🇿',
  'Uzbequistão': '🇺🇿',
  'Geórgia': '🇬🇪',
  'Armênia': '🇦🇲',
  'Azerbaijão': '🇦🇿',
  'Ucrânia': '🇺🇦',
  'Bielorrússia': '🇧🇾',
  'Lituânia': '🇱🇹',
  'Letônia': '🇱🇻',
  'Estônia': '🇪🇪',
  'Moldávia': '🇲🇩',
  'Albânia': '🇦🇱',
  'Macedônia do Norte': '🇲🇰',
  'Bósnia e Herzegovina': '🇧🇦',
  'Montenegro': '🇲🇪',
  'Kosovo': '🇽🇰',
  'Groenlândia': '🇬🇱',
  'Canadá': '🇨🇦',
  'Tchéquia': '🇨🇿',
  'Polónia': '🇵🇱',
  'Suriname': '🇸🇷',
  'Guiana': '🇬🇾',
  'Palestina': '🇵🇸',  
  'Territórios Palestinianos': '🇵🇸',
  
  // Países em inglês (fallback)
  'Brazil': '🇧🇷',
  'United States': '🇺🇸',
  'United States of America': '🇺🇸',
  'USA': '🇺🇸',
  'US': '🇺🇸',
  'United Kingdom': '🇬🇧',
  'UK': '🇬🇧',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Colombia': '🇨🇴',
  'Mexico': '🇲🇽',
  'Uruguay': '🇺🇾',
  'Paraguay': '🇵🇾',
  'Ecuador': '🇪🇨',
  'Bolivia': '🇧🇴',
  'Japan': '🇯🇵',
  'India': '🇮🇳',
  'South Korea': '🇰🇷',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Indonesia': '🇮🇩',
  'Malaysia': '🇲🇾',
  'Singapore': '🇸🇬',
  'Philippines': '🇵🇭',
  'Australia': '🇦🇺',
  'New Zealand': '🇳🇿',
  'Russia': '🇷🇺',
  'Turkey': '🇹🇷',
  'Greece': '🇬🇷',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Poland': '🇵🇱',
  'Czech Republic': '🇨🇿',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
  'Bulgaria': '🇧🇬',
  'Croatia': '🇭🇷',
  'Serbia': '🇷🇸',
  'Slovakia': '🇸🇰',
  'Slovenia': '🇸🇮',
  'Ireland': '🇮🇪',
  'Iceland': '🇮🇸',
  'Luxembourg': '🇱🇺',
  'Monaco': '🇲🇨',
  'Vatican': '🇻🇦',
  'Vatican City': '🇻🇦',
  'Cyprus': '🇨🇾',
  'Egypt': '🇪🇬',
  'South Africa': '🇿🇦',
  'Morocco': '🇲🇦',
  'Tunisia': '🇹🇳',
  'Algeria': '🇩🇿',
  'Kenya': '🇰🇪',
  'Ethiopia': '🇪🇹',
  'Nigeria': '🇳🇬',
  'Ghana': '🇬🇭',
  'Panama': '🇵🇦',
  'Nicaragua': '🇳🇮',
  'Dominican Republic': '🇩🇴',
  'Trinidad and Tobago': '🇹🇹',
  'United Arab Emirates': '🇦🇪',
  'UAE': '🇦🇪',
  'Saudi Arabia': '🇸🇦',
  'Qatar': '🇶🇦',
  'Oman': '🇴🇲',
  'Bahrain': '🇧🇭',
  'Jordan': '🇯🇴',
  'Lebanon': '🇱🇧',
  'Syria': '🇸🇾',
  'Iraq': '🇮🇶',
  'Iran': '🇮🇷',
  'Pakistan': '🇵🇰',
  'Bhutan': '🇧🇹',
  'Cambodia': '🇰🇭',
  'Mongolia': '🇲🇳',
  'Kazakhstan': '🇰🇿',
  'Uzbekistan': '🇺🇿',
  'Georgia': '🇬🇪',
  'Armenia': '🇦🇲',
  'Azerbaijan': '🇦🇿',
  'Ukraine': '🇺🇦',
  'Belarus': '🇧🇾',
  'Lithuania': '🇱🇹',
  'Latvia': '🇱🇻',
  'Estonia': '🇪🇪',
  'Moldova': '🇲🇩',
  'Albania': '🇦🇱',
  'North Macedonia': '🇲🇰',
  'Bosnia and Herzegovina': '🇧🇦',
  'Greenland': '🇬🇱',
  'Canada': '🇨🇦',
};

/**
 * Retorna o emoji da bandeira para um país
 * @param countryName - Nome do país (em português ou inglês)
 * @returns Emoji da bandeira ou 🗺️ se não encontrado
 */
export function getCountryFlag(countryName: string | undefined): string {
  if (!countryName) return '🗺️';
  
  // Tenta encontrar o país exato (case-insensitive)
  const normalized = countryName.trim();
  const flag = countryFlags[normalized] || countryFlags[normalized.toLowerCase()];
  
  if (flag) return flag;
  
  // Tenta encontrar por substring (para casos como "United States" vs "United States of America")
  const found = Object.keys(countryFlags).find(key => 
    normalized.toLowerCase().includes(key.toLowerCase()) || 
    key.toLowerCase().includes(normalized.toLowerCase())
  );
  
  if (found) return countryFlags[found];
  
  // Fallback: retorna emoji genérico de mapa
  return '🗺️';
}

